- name: Install Koji utils package
  package:
    name: koji-utils
    state: present

- name: copy /etc/koji-gc/koji-gc.conf
  copy:
    src: files/koji-gc.conf
    dest: /etc/koji-gc/koji-gc.conf
    owner: root
    group: root
    mode: "0644"

- name: enable koji-gc.timer
  service:
    name: koji-gc.timer
    enabled: true
