- name: Add yum repository to work around rhbz1661580
  yum_repository:
    name: bz1661580
    description: work around rhbz1661580
    baseurl: https://fedorapeople.org/~ktdreyer/bz1661580/
    gpgcheck: false
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 7

- name: Install the very latest requests-kerberos (rhbz1661580)
  package:
    name:
      - python-requests-kerberos
      - python2-kerberos
    state: latest  # noqa package-latest
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 7
  retries: 100
  delay: 3

- name: Install Koji utils package
  package:
    name: koji-utils
    state: present

- name: copy /etc/kojira/kojira.conf
  copy:
    src: files/kojira.conf
    dest: /etc/kojira/kojira.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart kojira

- name: start kojira
  service:
    name: kojira
    enabled: true
    state: started
