language: python
cache: pip
before_script:
- git clone --depth 1 https://github.com/ktdreyer/koji-ansible
- pushd koji-ansible && git log HEAD -1 --no-decorate && popd
- ln -s koji-ansible/library/ library
- ln -s koji-ansible/module_utils/ module_utils

jobs:
  include:
    - name: syntax check
      install: pip install ansible
      script:
        - ansible-playbook -i localhost, setup-koji.yml --syntax-check

    - name: ansible-lint
      install: pip install ansible-lint
      script:
        - ANSIBLE_LIBRARY=library ansible-lint -x 501 -v roles/*

    - name: molecule
      install: pip install docker molecule[ansible,docker]
      dist: focal
      script:
        - export ANSIBLE_MODULE_UTILS=$(pwd)/module_utils
        - export ANSIBLE_LIBRARY=$(pwd)/library
        - molecule test -d docker -s centos8
      services:
        - docker
