- name: set python values for el7
  set_fact:
    # No "python3" package name prefix.
    python_kdcproxy: python-kdcproxy
    # See /usr/lib/rpm/macros.d/macros.python2 for %python2_sitelib
    python_sitelib: /usr/lib/python2.7/site-packages
    mod_wsgi: mod_wsgi
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 7

- name: Add yum repository to work around rhbz1827758 for el8
  yum_repository:
    name: bz1827758
    description: work around rhbz1827758
    baseurl: https://fedorapeople.org/~ktdreyer/bz1827758/
    gpgcheck: false
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 8

- name: Install kdcproxy packages
  package:
    name:
      - httpd
      - mod_ssl
      - "{{ mod_wsgi }}"
      - "{{ python_kdcproxy }}"
    state: present
  retries: 100
  delay: 3

- name: copy /etc/httpd/conf.d/kdcproxy.conf
  template:
    src: kdcproxy-apache.conf.j2
    dest: /etc/httpd/conf.d/kdcproxy.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart httpd

- name: copy /etc/kdcproxy.conf
  copy:
    src: files/kdcproxy.conf
    dest: /etc/kdcproxy.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart httpd
